version: '3.7'

services:
    django_gunicorn:
        volumes:
            - static:/stilsoft/static
        env_file:
            - .env
        build:
            context: .
        expose:
            - 8000
    nginx:
        build: ./nginx
        volumes:
            - static:/stilsoft/static
        ports:
            -  "80:80"
        depends_on:
            - django_gunicorn

volumes:
    static: