# Generated by Django 4.2.3 on 2023-07-05 12:22

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('replenishment', 'Пополнение'), ('debiting', 'Списание')], max_length=13, verbose_name='Вид транзакции')),
                ('sum', models.PositiveIntegerField(verbose_name='Сумма')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2023, 7, 5, 15, 22, 0, 200837), verbose_name='Дата транзакции')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL, verbose_name='Изображение профиля')),
            ],
            options={
                'verbose_name': 'Транзакция',
                'verbose_name_plural': 'Транзакции',
            },
        ),
    ]
