# Generated by Django 4.2.3 on 2023-07-05 12:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 5, 15, 22, 11, 514391), verbose_name='Дата транзакции'),
        ),
    ]
